### ISSUE TITLE
won't install on "detritus"

### ISSUE THREAD

**Issue by asheenlevrai** [cosmocode/sqlite#32]
For some reason always says "Unable to identify extension directory, you need to download and install manually"

Tried to install manually (DLed the tar.gz file etc.) but got the same error?!?

Maybe it's just me. Don't know.
Best,
-a-

**Comment by splitbrain** [comment]
fixed in dokuwiki

**Comment by asheenlevrai** [comment]
I still get this message when trying to install from detritus:
"Unable to identify extension directory, you need to download and install manually"

**Comment by micgro42** [comment]
Do you have the most current dokuwiki Version? release_stable_2015-08-10**a**

**Comment by asheenlevrai** [comment]
No I didn't install the patch. Now I did and could thus install the plugin. Sorry for the inconvenience. Thanks for your help.
Best,
-a-
